schema_version = 1
language = "graphql"
revision = 1

[lexical]
line_comments = ["#"]
doc_comments = ["#"]
block_comment = ["\"\"\"", "\"\"\""]

[calls]
exclude = []

[generic]
braces = true
receivers = ["."]
definitions = [
    { keyword = "type", scope = "body" },
    { keyword = "interface", scope = "body" },
    { keyword = "union", scope = "body" },
    { keyword = "enum", scope = "body" },
    { keyword = "input", scope = "body" },
    { keyword = "scalar", scope = "body" },
    { keyword = "fragment", scope = "body" },
    { keyword = "query", scope = "body_with_docs" },
    { keyword = "mutation", scope = "body_with_docs" },
    { keyword = "subscription", scope = "body_with_docs" },
]
