schema_version = 1
language = "hyprlang"
revision = 1

[lexical]
line_comments = ["#"]
doc_comments = ["#"]

[calls]
exclude = ["if", "then", "else", "end", "begin", "return", "is", "as", "host", "hostname", "user", "bind", "exec"]
