schema_version = 1
language = "makefile"
revision = 1

[lexical]
line_comments = ["#"]
doc_comments = ["#"]

[calls]
exclude = ["if", "else", "endif", "then", "foreach", "include", "local", "function", "self", "true", "false", "null"]
